### ISSUE TITLE
Exported images have a transparent background

### ISSUE THREAD

**Issue by cyanzhong** [bestony/logoly#1]
<img width="664" alt="Screen Shot 2019-03-25 at 10 52 34 AM" src="https://user-images.githubusercontent.com/6745066/54892321-1ef2fc80-4eec-11e9-88e7-01ce4f44c20b.png">

From my understanding, the background color should be dark gray, what do you think?

**Comment by bestony** [comment]
yes, i will add a new option to export with dark background.

**Comment by bestony** [comment]
New Feature Online
