### ISSUE TITLE
Export to SVG format code

### ISSUE THREAD

**Issue by tarvos21** [bestony/logoly#114]
**Is your feature request related to a problem? Please describe.**
I want a logo with svg format, so I can use it in html directly.

**Describe the solution you'd like**
generate svg format

**Describe alternatives you've considered**

**Additional context**

**Comment by Rudxain** [comment]
I'm willing to open a PR for this. Seems "easy" (I guess?)

**Comment by bestony** [comment]
> I'm willing to open a PR for this. Seems "easy" (I guess?)

just write code and make a PR :lol

**Comment by Rudxain** [comment]
Ok lol. Where should I start? It seems I should edit /src/generator/Pornhub.vue

**Comment by vvirtues** [comment]
+1, waiting for this to happen

**Comment by bestony** [comment]
fixed by #403
