### ISSUE TITLE
On the website, once you delete the text in the Yellow bottom, you can no longer enter it.

### ISSUE THREAD

**Issue by horsefaced** [bestony/logoly#15]
网站上，一旦把文字全都删除，包括黄定部分的文字，然后光标移动到黄底外部，就没办法再移动到黄底内部添加文字了

<img width="264" alt="image" src="https://user-images.githubusercontent.com/953648/54960633-6df66b80-4f98-11e9-8381-18052d3340b9.png">
 运行环境safari，macos mojave

**Comment by bestony** [comment]
试试tab键？

**Comment by DC-Shi** [comment]
Windows下Chrome也有这问题，使用Tab或者Shift+Tab来回切换焦点的话应该可以回到这里。黑色部分的文字按下Tab就能切过去

**Comment by bestony** [comment]
fixed
