### ISSUE TITLE
不能设置尺寸，微信等平台都要的是方图或者圆图，这个长条的不能全部显示进去

### ISSUE THREAD

**Issue by TonyMistark** [bestony/logoly#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bestony** [comment]
Link #3

**Comment by bestony** [comment]
竖版已经 push ，等待自动部署

**Comment by zhz1237ok** [comment]
> 竖版已经 push ，等待自动部署

是否考虑圆形，因为即使是60pixel也很难把全部内容缩进有效范围当做QQ头像，而且像素低了清晰度也低了

**Comment by zhaojuntao** [comment]
我尝试了下，竖版导出的图片依不是旧方形图。

另外，我也有圆形图的需求和更改字体的需求。
