### ISSUE TITLE
The exported images are a bit blurry and not as clear as what you see on the screen.

### ISSUE THREAD

**Issue by yes1am** [bestony/logoly#275]
**Is your feature request related to a problem? Please describe.**

I want to export a clearer picture.

**Describe alternatives you've considered**

I found a related issue in dom-to-image, https://github.com/tsayen/dom-to-image/issues/69, and tried https://github.com/tsayen/dom-to-image/issues/69#issuecomment-486146688 locally. And the picture is clearer, but the **position** and **size** seems to be a little problematic.

For example:

The original exported image  
![logo (2)](https://user-images.githubusercontent.com/25051945/116640908-355ac480-a99e-11eb-996f-6406f7cb2d52.png)

The exported image  after i use the code mentioned in the comment: https://github.com/tsayen/dom-to-image/issues/69#issuecomment-486146688
![logo (4)](https://user-images.githubusercontent.com/25051945/116640915-3b50a580-a99e-11eb-93fe-93d2f8ca0854.png)

I've tried debugging the code, but no results yet.

**Comment by bestony** [comment]
fixed by #403
