### ISSUE TITLE
Looking for favicon? I have made one for you

### ISSUE THREAD

**Issue by AshutoshDash1999** [bestony/logoly#313]
**Is your feature request related to a problem? Please describe.**
The favicon you are using is probably from PornHub website and not your own.

**Describe the solution you'd like**
I have designed the following logo.
![logoly pro logo](https://user-images.githubusercontent.com/46455250/139055819-354f9240-de8a-4c61-8570-eb9ab952b694.png)

Shall I add it to the website as favicon?

**Comment by Rudxain** [comment]
Why is this still open? #314 was merged
