### ISSUE TITLE
Upgrade to Vue3

### ISSUE THREAD

**Issue by bestony** [bestony/logoly#341]
## What I will do ?

Upgrade Logoly from Vue2 to Vue3.

## Why I post this issue?

I want to know is here any one work on Vue2, may be must postpone your work.

## Time
will start at 2022-03-15 UTC+8:00 20:00

**Comment by bestony** [comment]
@yes1am @kentwood

**Comment by DaywisonSilva** [comment]
hi @bestony , can i add some meta data about your site? some things like og tags, metatags?
if u can create a issue with hacktoberfest label for me... thanks a lot!

**Comment by yldshv** [comment]
Done with https://github.com/bestony/logoly/pull/400
