### ISSUE TITLE
Onlyfans

### ISSUE THREAD

**Issue by Brocks404** [bestony/logoly#353]
can u make Onlyfans logo creator?

**Comment by bestony** [comment]
can u provide a smaple image for me ? i don't use only fans.

**Comment by Brocks404** [comment]
![image](https://user-images.githubusercontent.com/62523556/161944327-98656da2-f257-4350-8ac7-25866a5ce5a7.png)


It must be,
 Hoefler's [Gotham Light](https://www.typography.com/fonts/gotham/overview) for "Only"

"Fans" is [Marguerite](https://www.ffonts.net/Marguerite1.font?text=Fans)


should be a nice for "OnlyFriends" or other Only Plattforms :)

**Comment by yldshv** [comment]
@bestony you can close that after https://github.com/bestony/logoly/pull/401 is merged :)
