### ISSUE TITLE
cann't export at Windows 10  Chrome

### ISSUE THREAD

**Issue by cs2393629** [bestony/logoly#43]
win10 64位操作系统   谷歌浏览器  版本 66.0.3359.139（正式版本） （32 位）

**Comment by bestony** [comment]
我复现一下。

**Comment by cs2393629** [comment]
Failed to load data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXIAAAB3CAYAAAAenssOAAAer0lEQVR4Xu1dB5QVRdb+MBMFVCS5uiqwwiqCuqIILkGERYLAEARGYQgiShBZA0FkCSIigrpkEBBJCovoLwoYEDAgYXUJsktSUBaRKILEPd/reT9vnt1dVd393sybvnUO53icqttVX9X7+vatG/IAOANpgoAgIAgIAimLQB4h8pTdO5m4ICAICAIRBITI5SAIAoKAIJDiCAiRp/gGyvQFAUFAEBAilzMgCAgCgkCKIyBEnuIbKNMXBAQBQUCIXM6AICAICAIpjoAQeYpvoExfEBAEBAEhcjkDgoAgIAikOAJC5Cm+gTJ9QUAQEASEyOUMCAKCgCCQ4ggIkaf4Bsr0BQFBQBAQIpczIAgIAoJAiiMgRJ7iGyjTFwQEAUFAiFzOgCAgCAgCKY6AEHmKb6BMXxAQBAQBIXI5A4KAICAIpDgCQuQpvoEyfUFAEBAEhMjlDAgCgoAgkOIICJGn+AbK9AUBQUAQECKXMyAICAKCQIojIESe4hso0xcEBAFBQIhczoAgIAgIAimOgBB5im+gTF8QEAQEASFyOQOCQMAIFM4H9KwFVLkauLE0UKxQwA8QcSmBwJ5DwLqdwGdbgZFLgQO/JG7aQuSJw1YkhxCBuhWASelAycIhXLws2RGB7w8AGdOAResTA5IQeWJwFakhRKBOeeC97iFcuCxZG4F6oxND5kLk2lsgHQUBZwRoTtkwAChxsaAkCDgjQM38j88A+wM2swiRy6kTBAJAoEctYGTzAASJiFyPQM85wItLg12mEHmweIq0kCIwqyPQ4uaQLl6WbYTA7C+BlhOMhig7C5ErIZIOgoAage1DgCsvUfeTHoLAjp+Aq54KFgch8mDxFGkhReDMuJAuXJbtCYE8nT0NcxwkRB4sniItpAgIkYd04z0uW4jcALhx48ahSpUqriO2bNmCJk2aGEiVroLAbxEQIvd+Kr7aCcxfBzStBJQvAZxzjpmsk6eAf+4EDh+zH3d5IeC6EmYyE91biNwA4SVLlqBWrVquIzZs2IAKFSoYSJWugoAQeVBn4MwZYOQSoNcblsRqZYAHqwP3XA8Uyqv3FLr0tZ4EfLTZvv/UB4D02/RkJauXELkB0kLkBmAluGvBggVRp04d5MuXL8FPCkb8pk2bsGrVKm1hopFrQ5Wl4w8HgfQpwJKNWccXzQ+0usX6d+vvgfPOdZa/egfQ4BWAsuza8t5A1Wu9zS9Ro4TIDZDNaURev3599O3bN2XILBbqefPm4ZlnnjFAP2vXmjVrYtq0aShVqpRnGckcOGnSJHTo0EH7kX6I/J2vgX/t0n5Ujuz4u6JA08rABeeZTW/eGqCpy0UxTSKzOgA3lHaW+9Y/gUZ/N3uu195/LgvMyPCfgkGI3GAHchqRt23bFq+88gqonaZaMyW2+PUJkTvv+N/eAfq/lWonIut8O1cHRqYBeS/QX8f+I0DGdGD+WucxQxoDf70bONfFbj70XeCpf+g/10/PZpWBienAxZpmH6dnCZEb7IIQuQFYiq5C5O4A+dHIw0rkSzcC9451vqSsWBqY3REoV9wZ+1+OA91nAxOXB3fW3SR5eWHZyRMiN9gvIXIDsITIsyBg+uISIjfTyH89Afx1HjD6A+eD92JzoFtNIA+dpB2a6qIzuF+AJWlgQ6Bfff9ShcgNMBQiNwBLiFyI3MdxMdVU6XLYciKw8Qf7h9YoB0xvB5Qq4j4pymk2Dvj3Hh+TNxgalAeMELkB6ELkBmAJkQuR+zguJkR+6jTwzNsATUpO7bX2QOtb1RNyu+gseBEwvClQ7nK1nNge0z8HJq+wH/N+d+Cu8mby7HoLkRtgqEPkH374IXgRl4wml53itWJ3zsJmI9+2F2g1Efh8m/2vLu0mYFxroEh+9a/S7aLzpistj5dri6nlRHu42dyZonhhV4By/TYhcgMEV6xYgdtvv911xNKlS1G7dm0Dqd67CpG7E/mpU6dw9OhRnGGUSALbeeedh7x53d0OxEZutgG6Gnl8AFD8U0iWJN/qZdXPV1101r/eMs/ovBCiT/vxMHDfpN/6tfPvXl4MTqsQIlfv7//3WL9+PcqXd/8OymlEThL75ZdfcPr0aYOV+utKUiO5uTVTYouXpeN+uGvXLqSnp+ODD1xuwPwtNTJ64sSJyMjICHS9fi47fz4G/HoygIUB2LrXKin2tYtf+lP1gEcD1l0YsFPoIveLSa5QpY33ugsY3Ai48HyApM86lyzaYXfh6Ua6fFbjG4EudwIXuAQTxaO+64Bl9rGzud9dAZjRHrikgP+9EiI3wDAVifzw4cPo2rUrpk+fbrBSf111cBIid8fYD5H7272so7/ZDbSYYOUecWq69ucg50VZJGZ6qfSYYy+Z7oYzO5zNi7J9L9BmMsBgo8fqWIWsY/OwJPuiU/erQwc3IXIdlDL76BBUTtPIhcjDp5EbHGll1027gebj3TXy7CJylTYe627IC9Hn3ssa6HNvJetL4varLUJPZkQngX/6HuufmzukcoMyOwiR6yIFQIfIp06digceeMBAqveuOjZyIXIhcu8nDFjxH+CO4e4SgvK8MJmnHTHHjm9YEZjQBihWyPq/bu6JNHE8WRdYsQXok6SITs7phTSgZ0AmKSFyzdNTrVo1vP766yhd2iVJAwC/JgPN6US6CZG7X3aG1UZucoZUfXWIPDuSSLkRM90E3+gM1Mm8zmKwUJ8FwIjFzqsd1wZY8y0wbpkKkeD+HmQ5PyFyzX3RuVyjKCFyvS8Xvzjp7IcQuebhdummqgd5fSlgTifgDy5h7/5nkVXC0eNAz7nOpBt7wcmRyzZbwUJO2QzpnjioEdB1pr13SdDzj8oL8gUoRK65SzrEQQ+RCRMmoHPngOsuOcxRNHJ3jXz//v1YvHgxfv31V81d9tatTJkyyoIjpi+unHLZOeNz64LQqQXpQqeL/qxVQKfX7HOqMEUtXQTLZAbt0Eul22xg+mf20umeSBt/zT/oPl2/n1u4v07eF/0nAULkmmilpaVh7NixKFq0qOOI48ePY9iwYejfv7+mVH/dhMglIMjfCVKPVgUXBelCp54NsHM/0Hayc9EHHRmxfeK1d9Pxbv3dvGBqXwe8ngFcFlDiUiFyzZ3TIU0hcgtMnUthUw01fpt0vpA0tzYp3UzXmxM0cl4o9lsADF3kDFGHO4BRLYB8Bulm/QB+5Ffg4ZnAq5/6kWKNpVmIEZ9lDUPudZ+8ajtQ7yX73jTnPN8MyG+D2zl5ANr53YpfxEsVItfclfbt22PUqFEoUMDZe59RhAMGDMBzzz2nKdVfN52XS5i9VvyhG+zoRBL5Z1uBjx3KkvlZxYlTwKL1ljeHU6t6DVC3AnC+QZCMlzndWRaocrU1kheSD87wIiXrGNrFd/wETEhSylrdGXsxuwiRa6I7cOBAPP7447jgAmfVI9mkKUQuphUeX5UdW/OI5+husb7qQQTu0IechSv4tZFMTxUdkIXIdVDy2Of5559H9+7dXUPPhcgtcMW08ttDlkiNPGxEfvAo0GEa8MYabz/mqHtitWvdvV+8Sfc/SojcP4aOEnTyaSTL3S06SdHIRSMPo0bONY9cAjw619sPPnrBefqMELkTgqy9kdhUc972zveoBQsWoGHDhq5yciKR+154ggSYaqjx05DLzrOIhE0j58ppXqFHDYsoM4kVLyyL5AP2/2L9/7Xf2R/cWPdElT96go6+Uqxo5EqIvHdgBr0aNWq4CtiwYQMqVKjg/SGGI3U0ckORSeueDCIPix95GInc7qCePAU8uwjo51B4miaVsa2BVrdY+U2OnQAG/x/wxXb3Y89LXyYN23fEvV/R/ABJ2O/Fb+G8wNB7gasv0/85ymWnJlY6dt81a9bgpptu0pTov5sQuYToh9W0YvfrYTqB1pMtTxS71vEOYGRzIP+Fer89auwfbQb+/jHw9lfuY5gOYFgT4MYr9GSzF18872+wyF9Vgk4lVYhchRAQqfgzbZraHpvMzIecthC5ELkQufUD3n8E6DwDmLva/gd9XQmrwARNMW6N5LpxN8DUBK997vxSiJfRqCLAfC2XZybpUtEKXxLM/fLc+0DNcmZj7WQLkasQNyDMZGY+FCJXv1yTdWehcxFuakoyCQgiKbC6TZDtw2+AtPHOEmmmeLMzUPl3QT7VWRYDjvI6eP4yL/nE5VbYvlMb3wZg8JJdytjjJ4F13wELv7JeBN/819uaHroTeK6pWuP/bh/w+Dxg5qqzz+HXwrNNAJpnvDQhcg3UBg0ahN69e7v6kJ88eTISMPTYY49pSAymS5g18gYNGkQq8xQr5lxAMSxEHsxpOitFVT6NPf9cFpiRAZQsHPTTzeW5ZUKktPQqwEstgUKZ1fhYLOtf3wOfbrUCnpZuss/bYjqTeBt8/HjiunKLlZzLrlCH7otANHLTncnsP2vWLLRo0cJ1dLKjOsOukeu8xLZv347mzZtj1aoY1cfjGXAblt0aedBLopkiYzowf62zZJLOiDTgovODfrqZvENHgUdmAdMckmLZmVRUlYWcZkCibnMrsOVHy7Zt15xMOPxqoq2dZd8OH3NeY/eawODGaq0+XoJo5BrnZvXq1ahcubJrz4MHD+Khhx6K5CxPVtMhs2TNxfQ5pqaGePk6a0+WF1FuI/IvtgGNxzinfeVeZFdVoNhzwFwwLywB/vqm8+lzMqkwZwvHkVx1GrX6J+pa6XpX7wCajXe2n8d/AWz9EXjsTfcXY+wcJrS1zEAmTYhcgZbOJzxF7Ny5E/fddx8++eQTE/x99dUhs2RHm3JBOh4+ySDyQ4cOgVp5oluRIkVwxRXu7gqm6zWxkQe5Pl72Pb0QGPKuP6kDGwL96vuToRrN/DL3v6pPqPHyojU8nXLJUANvVhnoXcci8Kh9nSXmGIz0j3XOM+SLjmPnrgH6LtC7NL3lKmBIY+vyM7aWqAoH/l2IXIGSTmg+RSTb9ZDPDDORM1XwU089hQsv1PQl0/k1JLBPqhC5yt5MiGqUs7LzscalU0s0ke9iOtspAC9l7RpNHCz1Rhs+3REZKLT5v8C3+4DvD1qEyT4fbLLyrccWneCFY9tbgW41gd9fepbAfzwMvLgUGLtM7VNOl0KmqF2yUX2oiCVfFqwfqusaGS9ViNwF54IFC+Ljjz9GpUqVlLsxe/ZstGzZUtkvyA5hJnKdJGZBYu1XVioQuU5JNOIwoAFAInXLGphIIjc1i8TvXWzkJL9A6Ab4xHwrrW2nalbA0CUxSU5/+hmYvNIKNlIFBZmek3tuAJ5pAFS6wl8RZiFyF+SffPLJSJGIiy66yHV/kp2HPDqZMBP5uHHj0LFjR+QJogS56a/PQ/9UIHI77TR+qWWKAdPaWfnA3bIGJpLIadpoNRH4fJuHjQBw+zVWUYcrL7HGk5y3/wTcUCprDnBq76+uBEZ9EDyB87msTrSwK8AqS36bELkDgtTGGZZ/8803KzHes2cPOnTogIULFyr7BtkhzET+6quv4v777w8SzoTKyulEvvsg0GE68M7X7jA8cJvlK80w+Owicr85UtyqGlFD5wti/CfA/HXuHibU7HvWBqZ+6mziUR0qpgzoXF3VS/13IXIHjEaMGIFHHnkE55+v9q/iBWf16gHshnq/svQIM5EvWbIEtWrVMkQs+7rnZCLXveA0Sf+aSI2cu+gnv4wdke85BMxZbRH417vU56R9VWBwIyuSk5kYe72hHmPXo20V4JVW1p2DnyZEboNevXr1IsEmJUuWVGJ74sQJvPDCC3jiiSeUfYPuEGYi1/GMCRpvP/JyKpHTp5oRhqy44+bfzLWzPBlLo9F33K2KPfuaEjm1bKaV1b3s+2Y30GKCfWCNap/qX28VaGZ7bwMw4wt1LpWozHKXA0/fY2HBUmy8VxizDOg5x/mp9EahSyKjT+MDgWhe+UcX4E+/V83a/e9C5HH4lC9fHjNnzsQNN9ygheyOHTsil5yffeYQkaAlxVunsBL5XXfdBaZDKFGihDfgsmFUTiVylQtfFKqoNs7kUDqmDVMip7fMfZOsiFFeNjLdrFvNSj+1OzOqAqUKAyOXql9esetnEBRzmUcLJtOLZcBCtS/6rI7AX/5oRXROt6GJIApAC5HH/KhpF583b17kk13nEu306dMYP348unTpkg3UEF73w4cffhjPPvss8ud3TkzBC2iS56efBlClV7G7jDVIS0tz7ZUTiVyXxLmw2MyBiSDyZZuBO0echZCaL6Mom1YG+N92ftWTllt2/djGup7FC1k5YApcCPyxpJVWlhebhTLNF3wp0R2x82vAAhcXyqjceM8SfsUwvL/HHIAFllXtybrA3xpZGrldrVHO7Y1OwM1XqSQ5/12IPAYbanmtW7fGuefqVZLdtm1bJAgoO7RxTjusGjlJsV27dq4v22SmTEjFyE4SJ5NM6SSIiieaRBC5m82b2nnrP1nRjrGJs+gfTlMFPWnoL06iNnFiUvnM0yTy+N3APdcDF2ZelfFLYMzHwMB39LV5BgZNTAf+swdo8Ip9xGx8NKgppQuRA6AmPmbMmIiJRJfEaRt/6aWX0KtXL1PMA+sfRiLnXlHLVhXw2LdvHx588EHMneuxHpjBLqUSkVObZKKoLq/rRRsSBnqpMFjl3HMsUBJB5Kzq09+hIEREaQnoUjB2W53uB/gF8HhdoPlNZ2327MuqQ4x6VeUmjz860QRjtP+71RqNx9ngCEpkJ4mBNvG6detqkzgB/vLLLyN5yhkCn10tjETOfDbDhg1DgQIxERs2G5CshFl8dKoQObP+zfrSSjKlG9gSveAsEmPFCprImYK3+2zL9ODUeMHIfyYat87vMja4iAFBtFdTg469dKUtnEFDzMuiuhC2e2ZsAJKdOSg6hl8+Ux8A7iyrM/OsfUKtkVepUgWjR4+O+Irr2MSj0FHb69q1K5gVMTubDpH//PPPGD58OGgGSlbr168fypQp4/o4U5txVNiyZctQrVo15VJWrlyJqlWrKvsF0UHHp910vUHnWoktZKBLRjRpTLnfCmWPbUETOYmSF51u4ewkuPTbzHeLuca53u/2A7sOABt/ANZ/D+w9AjzfFChXHGBSqw0/ALX+kNV0Q4+UN9cCA99Wm6Aa3wiwJJyTH/7y3kDVawGVtw2/Bpjoq7ohmYeWyHlByajN4sWLG52OY8eORdwN+/TpYzQuEZ11iDwRzw1Cpimx8ZndunXDkCFDXC852e/MmTOYMmUKMjIygpiqUoaOT7vpeoMkcrtCBqpFuWmHOkTOQJln7wUuOE/1JCuboJPtmKN5Ofl+d4AXmbGNXxgHjwJHjgOM9tz789l8Kpv3AP/e42w+qn2dFd0Z9UCJl7tyKzDsPT0zyiM1rNSzzMPiZB6KEjkzNjKVLU1JTs0LmYeOyEuXLh3RUJs0aeJaKMIO5FOnTmHGjBk5JqIwTEROt9A5c+YobePctyNHjkT8+l9++WU1i/jswa86fpldeaV7nHV2EDmJ7t31QK+5ao0yFgZVgQQdIo9e8F2cWczBDWZGiNp5c0THxBaxYI4XpoRlPnBd85Dds+2CgojXmm+BIYv0Us4Sp75/AZhDnJehbnb+KJFzLjppgunmyVQIuqXjQkXk1NAGDBgAkrlpo5bHmpx8AWSnXTx23mEichOPomTZx3Uvyemmyst0uk3qNr8auR+7LjVp2oqd/Lh1iDzW79xtzaoshhzLEPaRaZbZg2YSJ39sXWzZL5bIGdlKd0L6lbsV04iVzy+W4U2BppUs10iacJh4i1Gedi2WyHWSk7mVprOTHwoiv/vuuyOf5BUrVjS60IwCRhL/6quvIq6GLFaQU1pYiJzaNc1gefOq1TvuFTVk7pVJq1+/Pvr27Ru5K9myZQv49RVt/G/u/969eyP/69JLL43cq9BWT6VAdb/iJamaVyKnVsnSZb3f9Bb1qCJxrl9FWlHcot4fjSsCsZel/DtNIl9uB178QG2+eCHNymnCRu8Rmib4z08jkY+5zyJwpqX95N/60qpeA4xumbVeKdfj5JHCS9Q5nayc5tHGtTsVp2CaYEaeliqiP6dcTeT87OXFG71LVBkMnSDLqSTO+YaByJkugUFXul9R+/fvj2i+ppWabrnllojp5qqrfERlOBwiL6YeL0TOQgl0j3Mqe+ZGC9SgWQiiZy33iMqoDJW7oD4FuffkvN59xLoojDZWuG85IagnmMl57C7gyXq/LZLsZi6Jz7bIJ7pVNzLVxikvVxO5yee43XaSxJcvXx7xR85Jmnh0rrmdyEniNEmo7M9RPLhfb7/9Nho2bGj268zsrXNp6UWwl+yYJkTuN182yZKmi/tv0yNxYjDtU6s6T6Jb3QrA9PbApTHepqrL0UTMiV8XgxoBTTJNKbHPoNdLt9nOHitOPvB2GSe9aOO5nshNQ+5jN4ef04sWLUKrVq1yjE08/oDmZiKnBv7WW29pFfWI4kLC5Et3/vz5nn7LutWgTIV7qR6lS+TU7EYtBQYoivo6zZkE9WJzy2Zs4qOdLDId0cwyq8TO7fsDQOtJwEeb9XaCFX/oy33zlVa4/zWXWZelQxfpjWfulx61gD4LAHoARfOYc/TRE8C679z9y//WEOjzF3t849MkeNHGcz2Rc4EkBGrmNWrUUNoyo9vK8G4GedDdLSe33EzkxL1NmzYYOnSollmFL96xY8caXSjG7y3zpVBG0aJFA9t2r9kxdYmcE+VlHXNiMyOhro84x9EzYlSLrLZb3YX7SVql+wz6sdNWXObyrCOcAohYZYd+4SRsFom4thhwWQGggE2KWJ0qQyT9/vdYF5p8kbhdZjqtSZXdMDa6lPM2tY1Hn5urTSvRRZpkNKRWR88WftLn9KZD5KkeEKQbtBVEpK1u+L/JuWC63ebNmxub5kyInPMhIdB2TI8OHbc8J1uvydpUuUpMZMX3VblATl5hJb66sbRF3sUK6vmsxz6HwUHtptpXGmLuE5Zgu+rSsyNUbpJ262UhjpdbuafnjZab45cD88mYfBmFisi5WNWlGe2rX3zxBXr06JFtSbBMD74OkdNVklGo06fHpYkzfZhBf51c4SZ+1ao0Cjt37kSnTp3w7rs+S78DWLBggWcbezxEBw4cAMsFUss3baZEHiVzVR4Vapkj0oB6FcwrtdutwST5li4GJDR6qjBRllsqW115bv1oYmk27uyXjFsl+/gMjarnm2Q15IuY/+yyPKqew7+HQiOPAkH7KT/VCxcunAWbgwcPRiIBe/bsqYNZjukTFiKPAj5hwgSkp6dnCeTyQ5Z2GxmUnXz37t2R6N/Jkyd7Oi9eiDxK5qws337ab6MamU+bhZPtohk9TTJzkEl1ebfnRKvX0x4dqwn7mZtqbFQbZnEIBvaw+LJTcQtmL2w50YpEVTW+MFnGjXlTvGjYKvnxfw8VkXPxgwcPxqOPPhpxR6QWvnbt2kgGw48++sgUu2zvHzYiJ+BPP/10ZL+opSciXUL79u0xatQoZVIuu83neeKLhV8GPGd+PJ28Enl0XrGaspuWGeQhpn/5lh+BrXutnCa8iFU1hvAzZzjt2Sz2oBPSr5Jp+nfeK5DQ433d4+XsPwK0neJe15QmIUa19q+fvJdR6DTy6Mbw8rN27dqRhFnMpJeqjRe5d9xxh2tdUV620YWS5odkNQbXqC4MN23ahFWrVnmaEsl20KBBWLx4ceDpEsqWLQtmWFTNP3biGzdujODrZ03xQPglcspjkAvzdbe7Xb+EmqcNCckgvqjeXAN8uy/rgq8oCpS8GCicD7j2MvvL1URDFDqNPNGAivzkIMCXGE1iOSVdQtCrDoLIg56TyMu5CAiR59y9kZmFGAEh8hBvvoelC5F7AE2GCAKJRkCIPNEI5y75QuS5az9lNbkEgd3D9VOY5pIlyzI8IvDfQ0Dx3h4HOwzLw9iEYEWKNEEgfAgs6maFzUsTBFQIvLceqDta1cvs70LkZnhJb0HAFgGmk2UBYGmCgAqBYYus9AFBNiHyINEUWaFFgFGB6/paLm3SBAEnBA4wTcEg55J2XpETIveKnIwTBOIQYEHf+V0EFkHAGYFGfwfe+mfwCAmRB4+pSAwxAszHPSkdKJk1q0SIEZGlEwGm8s2YBjC3TiKaEHkiUBWZoUaA5hVW7mEVeWb7K1Yo1HCEdvF7DgHrdgKfZdYXpVklUU2IPFHIilxBQBAQBJKEgBB5koCWxwgCgoAgkCgEhMgThazIFQQEAUEgSQgIkScJaHmMICAICAKJQkCIPFHIilxBQBAQBJKEgBB5koCWxwgCgoAgkCgEhMgThazIFQQEAUEgSQgIkScJaHmMICAICAKJQkCIPFHIilxBQBAQBJKEgBB5koCWxwgCgoAgkCgEhMgThazIFQQEAUEgSQgIkScJaHmMICAICAKJQkCIPFHIilxBQBAQBJKEgBB5koCWxwgCgoAgkCgEhMgThazIFQQEAUEgSQgIkScJaHmMICAICAKJQkCIPFHIilxBQBAQBJKEgBB5koCWxwgCgoAgkCgE/gdhGzLTKxi9kQAAAABJRU5ErkJggg==: Invalid response. Origin 'https://logoly.pro' is therefore not allowed access.

**Comment by cs2393629** [comment]
上面是浏览器中点击导出后的报错

**Comment by yisen** [comment]
我也同样无法导出，win 10, Chromium 版本 65.0.3325.181

**Comment by bestony** [comment]
get, i wiil fix it at new version

**Comment by bestony** [comment]
Hi @yisen & @cs2393629, I fix it at #40 & https://github.com/bestony/logoly/commit/af6c93c556a8d4a5750367d4f2f2e80c0df2a996 with @qiuquanwu ‘ method, now maybe you can download it. The new version is online right now.

**Comment by yldshv** [comment]
@bestony pls close this issue (its already fixed by you :D) ✅
