### ISSUE TITLE
博主啊! 你的readme.md里语法是错的啊

### ISSUE THREAD

**Issue by Cherrison** [bestony/logoly#46]
我一个小白, 试了很多次都不能把图片居中, 后来发现你这个语法是错的, 你的图片是一个长图片而不是居中显示
你写的是<p class="text-align:center;">
<img src="https://i.loli.net/2019/03/24/5c9681455a5a2.png" alt="logo" title="logo" />
</a>
而应该是这样的
<p align="center">
<img src="http://www.cheery.pro/images/logob.png" alt="logo" title="logo" />
</p>

**Comment by Cherrison** [comment]
这样...
<p>
<img src="http://www.cheery.pro/images/2019-04-26 22-20-33屏幕截图.png"> 
</p>

**Comment by bestony** [comment]
我后面更新一下看看

**Comment by bestony** [comment]
fix at https://github.com/bestony/logoly/commit/3d6cdf41f2cd9561c3735def7cdcb88753a2ba0d
