### ISSUE TITLE
Google Support

### ISSUE THREAD

**Issue by DevSum** [bestony/logoly#74]
How about add a support like google's logo.

Like this:
![logo](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1562604657581&di=fec14b710a0627f5b64fd24976b193b5&imgtype=0&src=http%3A%2F%2Fww1.sinaimg.cn%2Fwap720%2F966ee060jw1f20brkbc4bj20vl0hsjse.jpg)

**Comment by bestony** [comment]
It’s ok

**Comment by yldshv** [comment]
@bestony pls close this issue (Link is broken and thats not an issue) ✅
