### ISSUE TITLE
LOGO 字体导出成图片版权问题

### ISSUE THREAD

**Issue by tumobi** [bestony/logoly#87]
LOGO 字体导出成图片商用是否有版权问题？是否可以可以选择字体？或是默认提供无版权的字体。

**Comment by yldshv** [comment]
@bestony pls close this issue (its not an issue more a question and im sure the person is not waiting for an answer anymore :D) ✅

**Comment by bestony** [comment]
Currently, font selection is supported. You can choose according to your own needs. Copyright restrictions can follow the font itself.

目前已经支持字体的选择，你可以根据自己的需要选择自己。版权约束则跟随字体本身即可。
